# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bffc9bc2e97e4d2ba97eb0f7bdab3207164fd15e40d43a38f05ead2acb6e0291b175599201124e63bae04eb7ad137421f71ee72b13e81a787ee0dff465e61b2

test:
  secret_key_base: d0e92a1b687a4594dce951bae909cda6cd819fc749fa1458c7cefe95fbf1d9bdda6177720a547daccd8d4fef04b9aa6893185a48e1da2a7b746d7db3ae5ebe93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
